# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storyboardai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'storyboardai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12storyboardai.proto\x12\x0cstoryboardai\",\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\"\x1d\n\x0cTextResponse\x12\r\n\x05story\x18\x01 \x01(\t\"1\n\x0cImageRequest\x12\r\n\x05story\x18\x01 \x01(\t\x12\x12\n\nnum_images\x18\x02 \x01(\x05\"\x1f\n\rImageResponse\x12\x0e\n\x06images\x18\x01 \x03(\x0c\"\x1e\n\rAudioResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"F\n\x0cVideoRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x11\n\tvoiceover\x18\x02 \x01(\x0c\x12\x13\n\x0bmusic_track\x18\x03 \x01(\t\"\x1e\n\rVideoResponse\x12\r\n\x05video\x18\x01 \x01(\x0c\x32V\n\x0cStoryService\x12\x46\n\rGenerateStory\x12\x19.storyboardai.TextRequest\x1a\x1a.storyboardai.TextResponse2Y\n\x0cImageService\x12I\n\x0eGenerateImages\x12\x1a.storyboardai.ImageRequest\x1a\x1b.storyboardai.ImageResponse2W\n\x0cVoiceService\x12G\n\rGenerateVoice\x12\x19.storyboardai.TextRequest\x1a\x1b.storyboardai.AudioResponse2X\n\x0cVideoService\x12H\n\rGenerateVideo\x12\x1a.storyboardai.VideoRequest\x1a\x1b.storyboardai.VideoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storyboardai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=36
  _globals['_TEXTREQUEST']._serialized_end=80
  _globals['_TEXTRESPONSE']._serialized_start=82
  _globals['_TEXTRESPONSE']._serialized_end=111
  _globals['_IMAGEREQUEST']._serialized_start=113
  _globals['_IMAGEREQUEST']._serialized_end=162
  _globals['_IMAGERESPONSE']._serialized_start=164
  _globals['_IMAGERESPONSE']._serialized_end=195
  _globals['_AUDIORESPONSE']._serialized_start=197
  _globals['_AUDIORESPONSE']._serialized_end=227
  _globals['_VIDEOREQUEST']._serialized_start=229
  _globals['_VIDEOREQUEST']._serialized_end=299
  _globals['_VIDEORESPONSE']._serialized_start=301
  _globals['_VIDEORESPONSE']._serialized_end=331
  _globals['_STORYSERVICE']._serialized_start=333
  _globals['_STORYSERVICE']._serialized_end=419
  _globals['_IMAGESERVICE']._serialized_start=421
  _globals['_IMAGESERVICE']._serialized_end=510
  _globals['_VOICESERVICE']._serialized_start=512
  _globals['_VOICESERVICE']._serialized_end=599
  _globals['_VIDEOSERVICE']._serialized_start=601
  _globals['_VIDEOSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
